---
title: "dataset B summary"
author: "Peder M. Isager"
date: "11/1/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

data.B <- readRDS("../processed_data/dataset_B.rds")

## summary of key variables

key.vars <- c("PY", "study_number", "sample_size", "coder", "resolver", "excluded", "TC", "RV")

summary(data.B[, key.vars])

## visualization of key variables

coder.freq <- table(data.B$coder)
barplot(coder.freq, xlab = "Coder")  # Plot frequency of coders 

studyn.freq <- table(data.B$study_number)
barplot(studyn.freq, xlab = "Study number")  # Plot frequency of study numbers (first vs. second vs. fourth etc.)

pubyear.freq <- table(data.B$PY)
barplot(pubyear.freq, xlab = "Publication year")  # Plot frequency of publication years

hist(data.B$sample_size, breaks = 50, xlab = "Sample size", main = "")  # Plot sample size distribution

hist(data.B$TC, breaks = 50, xlab = "Citation count (WoS)", main = "")  # Plot citation count distribution

hist(data.B$RV, breaks = 50, xlab = "Replication value (C/Y)/(N-3)", main = "")  # Plot replication value distribution


```

